# Generated by Django 5.2.6 on 2025-09-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='assessmentanalytics',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradingrubric',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_detail', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='reviewed_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews', to='assessments.assessmentsubmission'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentsubmission'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['course', 'status'], name='assessments_course__6e055a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_type', 'status'], name='assessments_assessm_843194_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['due_date', 'status'], name='assessments_due_dat_0f73b7_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['student', 'submitted_at'], name='assessments_student_bb4a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['assessment', 'status'], name='assessments_assessm_6509f2_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmission',
            index=models.Index(fields=['graded_by', 'graded_at'], name='assessments_graded__0066a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsubmission',
            unique_together={('assessment', 'student', 'attempt_number')},
        ),
        migrations.AlterUniqueTogether(
            name='peerreview',
            unique_together={('reviewer', 'reviewed_submission')},
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={('submission', 'question')},
        ),
    ]
