# Generated by Django 5.2.6 on 2025-09-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, related_name='courses_assisted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursetagging',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tags', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursetagging',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_courses', to='courses.coursetag'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lesson'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='courses_cou_status_96f2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'created_at'], name='courses_cou_instruc_f1fbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty_level', 'status'], name='courses_cou_difficu_cb7647_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'status'], name='courses_enr_student_c86bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'enrolled_at'], name='courses_enr_course__e014c4_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['status', 'enrolled_at'], name='courses_enr_status_a26dae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='coursemodule',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['course', 'rating'], name='courses_rat_course__cad5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['is_approved', 'created_at'], name='courses_rat_is_appr_fad00e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='coursetagging',
            unique_together={('course', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='courses_les_enrollm_c8084f_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'completed_at'], name='courses_les_lesson__ed2d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
    ]
