# Generated by Django 5.2.6 on 2025-09-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementview',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='communications.announcement'),
        ),
        migrations.AddField(
            model_name='announcementview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communications.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='courses.course'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroommembership',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroommembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', through='communications.ChatRoomMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='communications.directmessage'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='courses.course'),
        ),
        migrations.AddField(
            model_name='forum',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='communications.forum'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='last_post_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='communications.forumtopic'),
        ),
        migrations.AddField(
            model_name='postvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='communications.forumpost'),
        ),
        migrations.AddField(
            model_name='postvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['course', 'is_published', '-publish_at'], name='communicati_course__12dda4_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type', 'priority'], name='communicati_announc_b49d75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementview',
            unique_together={('announcement', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', '-sent_at'], name='communicati_chat_ro_c39abb_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-sent_at'], name='communicati_sender__e51d78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroommembership',
            unique_together={('user', 'chat_room')},
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['sender', '-sent_at'], name='communicati_sender__45b2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['recipient', '-sent_at'], name='communicati_recipie_947377_idx'),
        ),
        migrations.AddIndex(
            model_name='directmessage',
            index=models.Index(fields=['thread_id', 'sent_at'], name='communicati_thread__6b0372_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['forum', 'status', '-last_post_at'], name='communicati_forum_i_68ce37_idx'),
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['is_sticky', '-last_post_at'], name='communicati_is_stic_da0eea_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['topic', 'post_number'], name='communicati_topic_i_d6d74b_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['author', '-created_at'], name='communicati_author__284ce3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumpost',
            unique_together={('topic', 'post_number')},
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together={('post', 'user')},
        ),
    ]
